algo = input('Digite algo: ')
print('Tipo primitivo:', type(algo))
print('Possui apenas letras?:', algo.isalpha())
print('Possui apenas números?:', algo.isnumeric())
print('Possui apenas letras ou números, ou os dois?:', algo.isalnum())
print('Possui apenas letras maiúsculas?:', algo.isupper())
print('Possui apenas letras minúsculas?:', algo.islower())
print('Está capitalizado?:', algo.istitle())
print('Possui apenas espaços?:', algo.isspace())
